// <auto-generated />
using System;
using ChaosCoordinator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChaosCoordinator.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722192101_ReplaceCheckedItemsHiddenBeforeWithToggle")]
    partial class ReplaceCheckedItemsHiddenBeforeWithToggle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChaosCoordinator.Domain.AccountToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("AccountTokens");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("AmountMax")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("AmountMin")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("BillingMonth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfirmationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagedById")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("PaidDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedById");

                    b.HasIndex("TemplateId", "BillingMonth")
                        .IsUnique();

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.BillPhotoBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BillId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HouseholdId", "CreatedAt");

                    b.ToTable("BillPhotoBatches");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.BillPhotoImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "Order");

                    b.ToTable("BillPhotoImages");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.BillTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("AmountMax")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("AmountMin")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("DueDay")
                        .HasColumnType("integer");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedById");

                    b.ToTable("BillTemplates");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.CalendarCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Order");

                    b.ToTable("CalendarCategories");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecurrenceDays")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("RecurrenceEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecurrenceFrequency")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RecurrenceInterval")
                        .HasColumnType("integer");

                    b.Property<int?>("RecurrenceMonthDay")
                        .HasColumnType("integer");

                    b.Property<int?>("RecurrenceWeekOrdinal")
                        .HasColumnType("integer");

                    b.Property<int?>("RecurrenceWeekday")
                        .HasColumnType("integer");

                    b.Property<string>("Reminders")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("TravelTimeLeaveBy")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("HouseholdId", "Start");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Chore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("AlarmTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<bool>("PhotoRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("RecurrenceDays")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RecurrenceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Chores");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.ChoreAssignment", b =>
                {
                    b.Property<Guid>("ChoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ChoreId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChoreAssignments");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.ChoreCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChoreId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompletedById")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompletedById");

                    b.HasIndex("ChoreId", "Date")
                        .IsUnique();

                    b.ToTable("ChoreCompletions");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.ChoreGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("DoneByTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Order")
                        .IsUnique();

                    b.ToTable("ChoreGroups");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.DietaryTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Tag")
                        .IsUnique();

                    b.ToTable("DietaryTags");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.EventAttendee", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("EventAttendees");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.EventException", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("EventId", "Date");

                    b.HasIndex("CategoryId");

                    b.ToTable("EventExceptions");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.EventImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("PastedText")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HouseholdId", "CreatedAt");

                    b.ToTable("EventImportBatches");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.EventImportImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "Order");

                    b.ToTable("EventImportImages");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BottomBarTabs")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.HouseholdTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("HouseholdTasks");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.MenuEater", b =>
                {
                    b.Property<Guid>("MenuEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("MenuEntryId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MenuEaters");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.MenuEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Dish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("HouseholdId", "Date", "MealType")
                        .IsUnique();

                    b.ToTable("MenuEntries");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.PriceHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("PriceHistoryEntries");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CookMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<int>("PrepMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.SavedLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Order");

                    b.ToTable("SavedLocations");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.SentReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "SourceId", "Key")
                        .IsUnique();

                    b.ToTable("SentReminders");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Checked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsCategoryHeader")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LastPaidPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "Name");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HideCheckedItemsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Substitution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DietaryLabel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Dish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ForUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ForUserId");

                    b.HasIndex("MenuEntryId");

                    b.ToTable("Substitutions");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.TaskClaim", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskClaims");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PinHash")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HouseholdId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.AccountToken", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Bill", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.User", "ManagedBy")
                        .WithMany()
                        .HasForeignKey("ManagedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChaosCoordinator.Domain.BillTemplate", "Template")
                        .WithMany("Bills")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ManagedBy");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.BillPhotoBatch", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.Bill", "Bill")
                        .WithMany("PhotoBatches")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ChaosCoordinator.Domain.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.BillPhotoImage", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.BillPhotoBatch", "Batch")
                        .WithMany("Images")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.BillTemplate", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.User", "ManagedBy")
                        .WithMany()
                        .HasForeignKey("ManagedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManagedBy");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.CalendarEvent", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.CalendarCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChaosCoordinator.Domain.EventImportBatch", "ImportBatch")
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChaosCoordinator.Domain.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ImportBatch");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Chore", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.ChoreGroup", "Group")
                        .WithMany("Chores")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.ChoreAssignment", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.Chore", "Chore")
                        .WithMany("Assignments")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChaosCoordinator.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chore");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.ChoreCompletion", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.Chore", "Chore")
                        .WithMany("Completions")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChaosCoordinator.Domain.User", "CompletedBy")
                        .WithMany()
                        .HasForeignKey("CompletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chore");

                    b.Navigation("CompletedBy");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.DietaryTag", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.User", "User")
                        .WithMany("DietaryTags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.EventAttendee", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.CalendarEvent", "Event")
                        .WithMany("Attendees")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChaosCoordinator.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.EventException", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.CalendarCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChaosCoordinator.Domain.CalendarEvent", "Event")
                        .WithMany("Exceptions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.EventImportBatch", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.EventImportImage", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.EventImportBatch", "Batch")
                        .WithMany("Images")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.MenuEater", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.MenuEntry", "MenuEntry")
                        .WithMany("Eaters")
                        .HasForeignKey("MenuEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChaosCoordinator.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.MenuEntry", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.Recipe", "Recipe")
                        .WithMany("MenuEntries")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.PriceHistoryEntry", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.ShoppingListItem", "Item")
                        .WithMany("PriceHistory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.ProjectTask", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChaosCoordinator.Domain.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.PushSubscription", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.ShoppingListItem", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.Store", "Store")
                        .WithMany("Items")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Substitution", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.User", "ForUser")
                        .WithMany()
                        .HasForeignKey("ForUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChaosCoordinator.Domain.MenuEntry", "MenuEntry")
                        .WithMany("Substitutions")
                        .HasForeignKey("MenuEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForUser");

                    b.Navigation("MenuEntry");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.TaskClaim", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.HouseholdTask", "Task")
                        .WithMany("Claims")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChaosCoordinator.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.User", b =>
                {
                    b.HasOne("ChaosCoordinator.Domain.Household", "Household")
                        .WithMany("Users")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Bill", b =>
                {
                    b.Navigation("PhotoBatches");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.BillPhotoBatch", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.BillTemplate", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.CalendarEvent", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Exceptions");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Chore", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Completions");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.ChoreGroup", b =>
                {
                    b.Navigation("Chores");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.EventImportBatch", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Household", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.HouseholdTask", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.MenuEntry", b =>
                {
                    b.Navigation("Eaters");

                    b.Navigation("Substitutions");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Recipe", b =>
                {
                    b.Navigation("MenuEntries");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.ShoppingListItem", b =>
                {
                    b.Navigation("PriceHistory");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.Store", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ChaosCoordinator.Domain.User", b =>
                {
                    b.Navigation("DietaryTags");
                });
#pragma warning restore 612, 618
        }
    }
}
